### ISSUE TITLE
Overtime scoring plays display out of order

### ISSUE THREAD

**Issue by ecormany** [saiemgilani/game-on-paper-app#153]
In the Scoring Plays section, plays that happen during overtime periods may appear out of order. For example: 
<img width="952" alt="Screenshot 2023-09-03 at 10 21 56 AM" src="https://github.com/saiemgilani/game-on-paper-app/assets/1958332/c7e02f0e-4f50-4bed-a878-8867c0fc492d">

Presumably this is because there is no game clock in OT and even when there are multiple overtimes, the API doesn't differentiate between them. A fallback sorting strategy could place these in the right order:

- Timestamp or object order in the API response (if these are reliable, but I suspect they aren't given the issue)
- Summing the scores and sorting by that number (cumbersome but always accurate)

**Comment by akeaswaran** [comment]
Thanks for this report! Looks like this was an issue in how our plays were ordered in general -- ESPN no longer marks multiple periods for CFB OT. To account for this, we've made some changes in our underlying parser and the proper play order should now be reflected on the live site.
