### ISSUE TITLE
Team season page seems to be mixing data from prior seasons

### ISSUE THREAD

**Issue by trueparallels** [saiemgilani/game-on-paper-app#157]
Clemson page is a good example. https://gameonpaper.com/cfb/year/2023/team/228

<img width="869" alt="image" src="https://github.com/saiemgilani/game-on-paper-app/assets/3158794/a9b745b4-03ce-41b5-adc7-f73cd25f2fdf">

![image](https://github.com/saiemgilani/game-on-paper-app/assets/3158794/ce46b55e-a84a-4fb4-ae1f-9289f0d2e5b6)

**Comment by trueparallels** [comment]
Looking at the data more closely, I think this might just straight up be 2022's data and not 2023's

**Comment by akeaswaran** [comment]
Weird, the microservice providing our team summaries has gone back to a version that doesn't have 2023 data. I'll rebuild and redeploy the app to see if this gets resolved.

**Comment by akeaswaran** [comment]
Ok, https://gameonpaper.com/cfb/year/2023/team/228 looks to have 2023 data now. Should be good to go. Thanks for reporting this!
